######################################################################
# Automatically generated by qmake (2.01a) Sat Mar 3 23:22:05 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += AudioThread.h Note.h SynthWindow.h
SOURCES += AudioThread.cpp freq.cpp main.cpp Note.cpp SynthWindow.cpp
